### PR TITLE
Fixing missing ftrSupportsCoherency flag setup for SVM support

### PR DESCRIPTION
**Pull request by FelipeMLopez**
This PR aims to complete the PR #53 made by @BartoszDunajski

### CODE REVIEW

**Comment by JacekDanecki** [comment]
Starting with Gen11, support for coherency is removed from underlying hardware, preventing us from supporting fine grain SVM. Support for fine grain SVM for Gen8/Gen9 hardware is still technically possible, however, as per community process, we are not allowed to merge this change to our userspace driver before patch to control data port coherency gets merged by the upstream kernel.

**Comment by FelipeMLopez** [comment]
Hi!
I see. Should I delete the pull request then?

**Comment by PiotrRozenfeld** [comment]
Given the benefits of this kernel change are limited to older hardware only, I expect it to get minor traction and chances it will get merged are fairly low.

The best course of action is to close the PR now, monitor the patch activity and revisit this conversation if it lands in upstream.

**Comment by FelipeMLopez** [comment]
Ok.
Thank you!

**Pull request closed without merging**
