### PR TITLE
build: Don't pass -q to ocloc during the build

### PR DESCRIPTION
**Pull request by mattst88**
This makes figuring out the cause of a failure very difficult.

### CODE REVIEW

**Review by JablonskiMateusz — COMMENTED** [review]
could you introduce new cmake flag (with NEO_ prefix) to control if `-q` should be passed?

**Comment by JablonskiMateusz** [comment]
> > could you introduce new cmake flag (with NEO_ prefix) to control if `-q` should be passed?
> 
> What is the advantage of suppressing potential error messages? I.e., why is making this optional appropriate?

We are assuming that kernels compilation failure is a very rare scenario, possible only when IGC component is updated or when kernel source is changed. Therefore we want to reduce build log, not to print success log every time. I see a value in printing the log in case of failures or any other issues related to compiled kernels but IMO it should be optional. The use cases are as follows:
- user builds neo project without any issues -> the log is minimal, no ocloc output
- user builds neo project with kernel compilation issues -> user toggles additional cmake flag to print ocloc output to analyze the root-cause

**Comment by mattst88** [comment]
`ocloc` prints `Build succeeded.` on success. That's what you want to avoid appearing in the build logs?

If you want to reduce the build output, perhaps dropping the `Build succeeded.'  message unconditionally is the right thing to do rather than suppressing potential errors. Compilers don't typically print a message on success.

Optimizing for build log size doesn't make any sense to me, especially when it can lead to a couple of hours of debugging in the case something is not working.

**Comment by thesamesam** [comment]
In addition, I've never seen a project default to suppressing errors. If you would instead like to make "Build succeeded" gated behind some verbose option, that might make sense (even if I don't like it), but I see it as noise.

The general expectation is that tools will either emit useful output or be silent, unless errors occur.

The motivation behind this PR is we've had _several_ confusing bugs where the build log is completely useless in determining the problem - and part of the time wasted on it was because compute-runtime behaved unexpectedly with its quiet-by-default-even-on-errors behaviour. It's very counterintuitive, unfortunately.

**Comment by JablonskiMateusz** [comment]
btw, since https://github.com/intel/compute-runtime/commit/f0a9533c83ce5c2f4d7296640a482cb40d7991b5 `-q` doesn't silence errors, `-qq` does it

**Comment by mattst88** [comment]
It looks like some unit tests (e.g. `opencl/test/unit_test/offline_compiler/ocloc_api_tests.cpp` require finding `Build succeeded`) in the output, so I cannot trivially remove the message.

I think it's patently absurd to optimize for minimizing build logs at the cost of providing no error messages, but I'm not going to spend my time trying to argue that point further.

Feel free to close the PR if you're happy with the current trade-off.

**Comment by JablonskiMateusz** [comment]
@mattst88  Right now, we are not printing "Build succeeded" during build while we are printing error on kernel compilation. I hope this trade-off resolves your problem with finding error from build log.

**Pull request closed without merging**
