### PR TITLE
feature: add experimental support for cl-gl sharing on Linux

### PR DESCRIPTION
**Pull request by JablonskiMateusz**
based on 'clgl-fork' branch from https://github.com/kallaballa/compute-runtime

EGL headers taken from https://github.com/KhronosGroup/EGL-Registry revision: 57b4876de0f33677ece92dd9de0ef105ce69139d

Related-To: NEO-3599

Fixes https://github.com/intel/compute-runtime/issues/166

Co-authored-by: Jacek Danecki <jacek.danecki@intel.com>
Co-authored-by: Amir Hassan <amir@viel-zu.org>

Signed-off-by: Mateusz Jablonski <mateusz.jablonski@intel.com>

### CODE REVIEW

**Comment by kallaballa** [comment]
I have issues building this.
With:
```bash
cmake -DCMAKE_BUILD_TYPE=Release -DNEO_ENABLE_i915_PRELIM_DETECTION=ON ..
make -j8
```
I get:
```bash
In file included from /home/elchaschab/build/intel-neo/new-compute-runtime/shared/test/common/test_macros/hw_test.h:719,
                 from /home/elchaschab/build/intel-neo/new-compute-runtime/opencl/test/unit_test/offline_compiler/offline_compiler_tests.cpp:27:
/home/elchaschab/build/intel-neo/new-compute-runtime/shared/test/common/test_macros/header/common_matchers.h:68:25: error: ‘IGFX_METEORLAKE’ was not declared in this scope; did you mean ‘IGFX_JASPERLAKE’?
   68 | using IsMTL = IsProduct<IGFX_METEORLAKE>;
      |                         ^~~~~~~~~~~~~~~
      |                         IGFX_JASPERLAKE
/home/elchaschab/build/intel-neo/new-compute-runtime/shared/test/common/test_macros/header/common_matchers.h:68:40: error: template argument 1 is invalid
   68 | using IsMTL = IsProduct<IGFX_METEORLAKE>;
      |                                        ^
/home/elchaschab/build/intel-neo/new-compute-runtime/shared/test/common/test_macros/header/common_matchers.h:75:39: error: ‘IGFX_METEORLAKE’ was not declared in this scope; did you mean ‘IGFX_JASPERLAKE’?
   75 | using IsAtLeastMtl = IsAtLeastProduct<IGFX_METEORLAKE>;
      |                                       ^~~~~~~~~~~~~~~
      |                                       IGFX_JASPERLAKE
/home/elchaschab/build/intel-neo/new-compute-runtime/shared/test/common/test_macros/header/common_matchers.h:75:54: error: template argument 1 is invalid
   75 | using IsAtLeastMtl = IsAtLeastProduct<IGFX_METEORLAKE>;
      |
```

Also tried:
```bash
cmake -DCMAKE_BUILD_TYPE=Release -DNEO_ENABLE_i915_PRELIM_DETECTION=ON -DSUPPORT_MTL=OFF -DTESTS_MTL=OFF -DTESTS_XE_HP_CORE=OFF -DSUPPORT_XE_HPC_CORE=OFF -DSUPPORT_XE_HPG_CORE=OFF -DTESTS_XE_HPC_CORE=OFF -DTESTS_XE_HPG_CORE=OFF -DTESTS_XE_HP_SDV=OFF ..
```
but that didn't fix the issue.

any ideas?

**Comment by frantisekz** [comment]
> I am on openSUSE Tumbleweed (VERSION="20230224"), x86_64, Tigerlake I am using Clang 11.0.1
> 
> I have issues building this. With:
> 
> ```shell
> cmake -DCMAKE_BUILD_TYPE=Release -DNEO_ENABLE_i915_PRELIM_DETECTION=ON ..
> make -j8
> ```
> 
> I get:
> 
> ```shell
> In file included from /home/elchaschab/build/intel-neo/new-compute-runtime/shared/test/common/test_macros/hw_test.h:719,
>                  from /home/elchaschab/build/intel-neo/new-compute-runtime/opencl/test/unit_test/offline_compiler/offline_compiler_tests.cpp:27:
> /home/elchaschab/build/intel-neo/new-compute-runtime/shared/test/common/test_macros/header/common_matchers.h:68:25: error: ‘IGFX_METEORLAKE’ was not declared in this scope; did you mean ‘IGFX_JASPERLAKE’?
>    68 | using IsMTL = IsProduct<IGFX_METEORLAKE>;
>       |                         ^~~~~~~~~~~~~~~
>       |                         IGFX_JASPERLAKE
> /home/elchaschab/build/intel-neo/new-compute-runtime/shared/test/common/test_macros/header/common_matchers.h:68:40: error: template argument 1 is invalid
>    68 | using IsMTL = IsProduct<IGFX_METEORLAKE>;
>       |                                        ^
> /home/elchaschab/build/intel-neo/new-compute-runtime/shared/test/common/test_macros/header/common_matchers.h:75:39: error: ‘IGFX_METEORLAKE’ was not declared in this scope; did you mean ‘IGFX_JASPERLAKE’?
>    75 | using IsAtLeastMtl = IsAtLeastProduct<IGFX_METEORLAKE>;
>       |                                       ^~~~~~~~~~~~~~~
>       |                                       IGFX_JASPERLAKE
> /home/elchaschab/build/intel-neo/new-compute-runtime/shared/test/common/test_macros/header/common_matchers.h:75:54: error: template argument 1 is invalid
>    75 | using IsAtLeastMtl = IsAtLeastProduct<IGFX_METEORLAKE>;
>       |
> ```
> 
> Also tried:
> 
> ```shell
> cmake -DCMAKE_BUILD_TYPE=Release -DNEO_ENABLE_i915_PRELIM_DETECTION=ON -DSUPPORT_MTL=OFF -DTESTS_MTL=OFF -DTESTS_XE_HP_CORE=OFF -DSUPPORT_XE_HPC_CORE=OFF -DSUPPORT_XE_HPG_CORE=OFF -DTESTS_XE_HPC_CORE=OFF -DTESTS_XE_HPG_CORE=OFF -DTESTS_XE_HP_SDV=OFF ..
> ```
> 
> but that didn't fix the issue.
> 
> any ideas?

I'd say try to use the latest gmmlib.

**Comment by kallaballa** [comment]
I'm back on it and i got the build working but i had to disable MTL and patched it a bit: 7193bf96aa77be62fd688e7711e131c7bb726f76

I used the following cmake line:
```bash
cmake -DCMAKE_BUILD_TYPE=Debug -DNEO_CPACK_GENERATOR=TGZ -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_RUNSTATEDIR=/run -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=lib64 -DNEO_OCL_VERSION_MAJOR=22 -DNEO_OCL_VERSION_MINOR=53 -DNEO_VERSION_BUILD=25242.13 -DDO_NOT_RUN_AUB_TESTS=FALSE -DNEO_SKIP_UNIT_TESTS=1 -DNEO_ENABLE_i915_PRELIM_DETECTION=TRUE -DNEO_DISABLE_BUILTINS_COMPILATION=FALSE -DRELEASE_WITH_REGKEYS=FALSE -DIGDRCL_FORCE_USE_LIBVA=FALSE -DNEO_SKIP_OCL_UNIT_TESTS=1 -DDISABLE_WDDM_LINUX=1 -DBUILD_WITH_L0=1 -DNEO_DISABLE_LD_GOLD=1 -Wno-dev -DCOMPILE_BUILT_INS=OFF -DSUPPORT_MTL=OFF ..
```
Anyway, my [Viz2D demos](https://github.com/kallaballa/Viz2D#tetra-demo) fail at attempting clgl interop.
Investigating.

**Comment by kallaballa** [comment]
I fixed two more issues i found: ac773325042a52862681939fd8be47347421ef6a and 47e1cd755e98ac6b3e476e19726ba06c7b33176d

but now it fails to load ```eglExportDMABUFImageMESA```.
Still investigating.

**Comment by kallaballa** [comment]
Fixed the EGL issue (f2c45d0fb363bcb1658ec101bc8d46ee1b9ff514) and now my demos work using cl-gl sharing.

Anyway could you assist me with performing a full test? or is there maybe a CI with tests?

**Comment by kallaballa** [comment]
btw. this is the branch i am working on: https://github.com/kallaballa/compute-runtime/tree/new-clgl-fork

**Comment by kallaballa** [comment]
On platforms without WGL glHdcHandle won't be set 

https://github.com/intel/compute-runtime/blob/ac773325042a52862681939fd8be47347421ef6a/opencl/source/sharings/gl/cl_gl_api.cpp#L334-L336

but glHglrcHandle will e.g. on Linux/EGL

https://github.com/intel/compute-runtime/blob/ac773325042a52862681939fd8be47347421ef6a/opencl/source/sharings/gl/cl_gl_api.cpp#L331-L333

**Comment by JablonskiMateusz** [comment]
Thanks, I rebased the change and applied your fixes

**Comment by JablonskiMateusz** [comment]
@kallaballa 
> Anyway could you assist me with performing a full test? or is there maybe a CI with tests?

Could you please re-verify that your demos work fine with the latest patch? (I didn't apply meteorlake specific commit, please update gmmlib-dev in your workspace to make it work - you may take it from recent release). 
I don't know if there are any cl-gl sharing tests to ensure conformance. Can we proceed with this change if demos are working fine while tracking any new further issues in Issues section?

**Comment by kallaballa** [comment]
> @kallaballa
> 
> > Anyway could you assist me with performing a full test? or is there maybe a CI with tests?
> 
> Could you please re-verify that your demos work fine with the latest patch? (I didn't apply meteorlake specific commit, please update gmmlib-dev in your workspace to make it work - you may take it from recent release). 

Sure.

>I don't know if there are any cl-gl sharing tests to ensure conformance. Can we proceed with this change if demos are working fine while tracking any new further issues in Issues section?

Fine with me.

**Comment by kallaballa** [comment]
I installed ```libigdgmm-dev_22.3.0_amd64.deb```.
I am again working in: https://github.com/kallaballa/compute-runtime/tree/new-clgl-fork
One fix is missing from the rebase: 5e04e796b88a4f84e5849bd4a738f08f059093b2
Without the fix i get the following error:
```bash
/home/elchaschab/build/intel-neo/compute-runtime/shared/source/compiler_interface/igc_platform_helper.cpp: In function ‘void NEO::populateIgcPlatform(IgcPlatformType&, const HardwareInfo&) [with IgcPlatformType = IGC::Platform<2>]’:
/home/elchaschab/build/intel-neo/compute-runtime/shared/source/compiler_interface/igc_platform_helper.cpp:25:5: error: invalid use of incomplete type ‘struct IGC::Platform<2>’
   25 |     igcPlatform.SetProductFamily(hwInfo.platform.eProductFamily);
      |     ^~~~~~~~~~~
In file included from /usr/local/include/igc/ocl_igc_interface/platform.h:14,
                 from /usr/local/include/igc/ocl_igc_interface/platform_helper.h:14,
                 from /home/elchaschab/build/intel-neo/compute-runtime/shared/source/compiler_interface/igc_platform_helper.cpp:14:
/usr/local/include/igc/ocl_igc_interface/platform.h:24:23: note: declaration of ‘struct IGC::Platform<2>’
   24 | CIF_DECLARE_INTERFACE(Platform, "PLATFORM")
      |                       ^~~~~~~~
/usr/local/include/igc/cif/cif/macros/enable.h:27:12: note: in definition of macro ‘CIF_DECLARE_INTERFACE’
   27 |     struct NAME;                                                   \
      |            ^~~~
```
and as far as i can see there is only one platform defined in /usr/local/include/igc/ocl_igc_interface/platform.h

**Comment by kallaballa** [comment]
works with the demos.

**Comment by JablonskiMateusz** [comment]
> I installed `libigdgmm-dev_22.3.0_amd64.deb`. I am again working in: https://github.com/kallaballa/compute-runtime/tree/new-clgl-fork One fix is missing from the rebase: [4a5def1](https://github.com/intel/compute-runtime/commit/4a5def118bcdb366e29b2af6563187037aa2dc6f) Without the fix i get the following error:
> 
> ```shell
> /home/elchaschab/build/intel-neo/compute-runtime/shared/source/compiler_interface/igc_platform_helper.cpp: In function ‘void NEO::populateIgcPlatform(IgcPlatformType&, const HardwareInfo&) [with IgcPlatformType = IGC::Platform<2>]’:
> /home/elchaschab/build/intel-neo/compute-runtime/shared/source/compiler_interface/igc_platform_helper.cpp:25:5: error: invalid use of incomplete type ‘struct IGC::Platform<2>’
>    25 |     igcPlatform.SetProductFamily(hwInfo.platform.eProductFamily);
>       |     ^~~~~~~~~~~
> In file included from /usr/local/include/igc/ocl_igc_interface/platform.h:14,
>                  from /usr/local/include/igc/ocl_igc_interface/platform_helper.h:14,
>                  from /home/elchaschab/build/intel-neo/compute-runtime/shared/source/compiler_interface/igc_platform_helper.cpp:14:
> /usr/local/include/igc/ocl_igc_interface/platform.h:24:23: note: declaration of ‘struct IGC::Platform<2>’
>    24 | CIF_DECLARE_INTERFACE(Platform, "PLATFORM")
>       |                       ^~~~~~~~
> /usr/local/include/igc/cif/cif/macros/enable.h:27:12: note: in definition of macro ‘CIF_DECLARE_INTERFACE’
>    27 |     struct NAME;                                                   \
>       |            ^~~~
> ```
> 
> and as far as i can see there is only one platform defined in /usr/local/include/igc/ocl_igc_interface/platform.h

Please install also igc devel package, it should resolve the issue [intel-igc-opencl-devel_1.0.12812.26_amd64.deb](https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.12812.26/intel-igc-opencl-devel_1.0.12812.26_amd64.deb)

**Comment by kallaballa** [comment]
Indeed!

**Comment by kallaballa** [comment]
I hit another issue: 
```bash
Abort was called at 91 line in file:
/home/elchaschab/build/intel-neo/new-compute-runtime/opencl/source/built_ins/builtins_dispatch_builder.h
```

I want to make sure it isn't another dependency and install all the packages from the latest release.

**Comment by kallaballa** [comment]
as describe [here](https://github.com/intel/compute-runtime/releases/tag/22.53.25242.13) I downloaded the packages and installed them:
```bash
mkdir neo
cd neo
wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.12812.26/intel-igc-core_1.0.12812.26_amd64.deb
wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.12812.26/intel-igc-opencl_1.0.12812.26_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/22.53.25242.13/intel-level-zero-gpu-dbgsym_1.3.25242.13_amd64.ddeb
wget https://github.com/intel/compute-runtime/releases/download/22.53.25242.13/intel-level-zero-gpu_1.3.25242.13_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/22.53.25242.13/intel-opencl-icd-dbgsym_22.53.25242.13_amd64.ddeb
wget https://github.com/intel/compute-runtime/releases/download/22.53.25242.13/intel-opencl-icd_22.53.25242.13_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/22.53.25242.13/libigdgmm12_22.3.0_amd64.deb

sudo dpkg -i *.deb
```

Problem still persists. Debugging.

**Comment by kallaballa** [comment]
The problem could be because of installing of [intel-igc-opencl-devel_1.0.12812.26_amd64.deb](https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.12812.26/intel-igc-opencl-devel_1.0.12812.26_amd64.deb).

I'll start with a fresh install and track down when the problem arises.

**Comment by kallaballa** [comment]
I verified it works with the packages for ```22.43.24558```

**Comment by kallaballa** [comment]
Starting from a fresh install it turned out that it actually works with ```22.53.25242.13```. I am not sure what the mistake was.

**Comment by nyanmisaka** [comment]
Merged in https://github.com/intel/compute-runtime/commit/9b35ba5e50ea1998bd1a7e0677115d20f994081e

**Comment by kallaballa** [comment]
awesome!

**Pull request closed without merging**
