### PR TITLE
Add information about Neo for Exherbo Linux

### PR DESCRIPTION
**Pull request by tgurr**
https://git.exherbo.org/summer/packages/dev-libs/intel-compute-runtime/index.html

### CODE REVIEW

**Comment by JacekDanecki** [comment]
Can you make optional dependency on:
- x11-dri/libdrm[video_drivers:intel]
- x11-libs/libva[>=2.0.0]
- x11-dri/mesa[-opencl]

How did you resolve test issue during llvm-8 build?
```
Failing Tests (1):
    LLVM :: ThinLTO/X86/cfi-devirt.ll

  Expected Passes    : 28428
  Expected Failures  : 150
  Unsupported Tests  : 770
  Unexpected Failures: 1
```

**Comment by tgurr** [comment]
> Can you make optional dependency on:
> 
> * x11-dri/libdrm[video_drivers:intel]

Having had a second look at it it seems compute-runtime doesn't require libdrm at all? If so then I'll gladly remove the dependency alltogether. Is there any reason not to rely on the headers of libdrm instead of shipping them bundled via `third_party/uapi/drm/*`?

> * x11-libs/libva[>=2.0.0]

To make libva optional, since we're a source-based distribution, we would need a CMake switch for it to be able to hard-disable it if not wanted, else it will become automagic if the library is present during build time.

> * x11-dri/mesa[-opencl]

We made this decision since if mesa is build with opencl the file `/etc/OpenCL/vendors/mesa.icd` will be present and users will run into segfaults with NEO due to:
https://bugs.llvm.org/show_bug.cgi?id=30587
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=852746
And as far as I know the opencl implementation shipped within mesa itself isn't very useful at all for intel hardware at the moment(?).

> How did you resolve test issue during llvm-8 build?

We currently just build with tests disabled (-DSKIP_UNIT_TESTS:BOOL=TRUE) due to having problems with them.

**Comment by JacekDanecki** [comment]
We don't use libdrm directly, so you can remove dependency. Actually we depend on kernel headers, not on libdrm headers, see https://github.com/intel/compute-runtime/commit/963049c988493736df2377e81d3db383812c397a#diff-0e4fb4b07a74572e1570ccd33b5985aa
When Neo is compiled with libva support, libva will use libdrm.

> To make libva optional, since we're a source-based distribution, we would need a CMake switch for it to > be able to hard-disable it if not wanted, else it will become automagic if the library is present during build time.

I can prepare such change.

> We made this decision since if mesa is build with opencl the file `/etc/OpenCL/vendors/mesa.icd` will be > present and users will run into segfaults with Neo due to:

I thought about removing dependency on mesa, as Neo doesn't need it to run.

> And as far as I know the opencl implementation shipped within mesa itself isn't very useful at all for intel hardware at the moment(?).

I'm not familiar with this implementation.
 
> > How did you resolve test issue during llvm-8 build?
> 
> We currently just build with tests disabled (-DSKIP_UNIT_TESTS:BOOL=TRUE) due to having problems with them.

I can't see such parameter in llvm build scripts. I was building llvm separately. Is this parameter forwarded to llvm build from Neo configuration?

**Comment by JacekDanecki** [comment]
Merged with 5023be247970ff76d8b51e8a1daff53463b54cbf

**Comment by tgurr** [comment]
> We don't use libdrm directly, so you can remove dependency. Actually we depend on kernel headers, not on libdrm headers, see [963049c#diff-0e4fb4b07a74572e1570ccd33b5985aa](https://github.com/intel/compute-runtime/commit/963049c988493736df2377e81d3db383812c397a#diff-0e4fb4b07a74572e1570ccd33b5985aa)
> When Neo is compiled with libva support, libva will use libdrm.

Oh alright, thanks for the clarification, looks like I got misleaded by the name LIBDRM_DIR in the CMakeList.txt. I've removed the wrong dependency on libdrm in a follow up commit http://git.exherbo.org/hardware.git/commit/?id=bb66558a2048482db24265117ec52fa409fc00bb. The package website mentioned above might need some time to reflect that change.

> > To make libva optional, since we're a source-based distribution, we would need a CMake switch for it to  be able to hard-disable it if not wanted, else it will become automagic if the library is present during build time.
> 
> I can prepare such change.

That would be great, then we can add an option for it and properly depend on libva depending on the option being enabled or disabled in our package.

> > We made this decision since if mesa is build with opencl the file `/etc/OpenCL/vendors/mesa.icd` will be > present and users will run into segfaults with Neo due to:
> 
> I thought about removing dependency on mesa, as Neo doesn't need it to run.

You're perfectly right, I understood that, the run dependency on mesa is just to make sure our package manager does the right thing and users won't end up having an opencl-enabled mesa plus neo and start wondering why opencl stuff segfaults when trying to run. It's a workaround until the LLVM issue with having multiple opencl providers around (https://bugs.llvm.org/show_bug.cgi?id=30587) is fixed.
I've a comment note regarding that in our package:
http://git.exherbo.org/hardware.git/tree/packages/dev-libs/intel-compute-runtime/intel-compute-runtime-19.25.13237-r1.exheres-0
The other option I firsted opted for was to just add a note users get diplayed when installing Neo about having to remove the `/etc/OpenCL/vendors/mesa.icd`, but that would mean they're to remember about it and do this every time mesa gets updated and the icd file gets installed again. So this is just to make sure if one sets the global option "opencl" users won't end up getting a borked setup. And since as far as I know the mesa opencl implementation is far from perfect I guess it won't hurt any users. If there'll be a user complaint about pulling in mesa and we need to change things we might turn this into a recommendation instead, but for now I just wanted to be on the safe side. Hope my explanation does make any sense to you.

> > > How did you resolve test issue during llvm-8 build?
> > 
> > We currently just build with tests disabled (-DSKIP_UNIT_TESTS:BOOL=TRUE) due to having problems with them.
> 
> I can't see such parameter in llvm build scripts. I was building llvm separately. Is this parameter forwarded to llvm build from Neo configuration?

Oh I thought you were talking about neo where we currently disable the tests and pass -DSKIP_UNIT_TESTS:BOOL=TRUE. You mean with the build of llvm itself? I'm sorry I cant answer that as I don't maintain llvm on our distribution.

**Comment by JacekDanecki** [comment]
I understand why mesa is installed now, thanks for clarification. For llvm problem I'll file issue in exherbo gitlab.
Closing pull request, as it was merged.

**Comment by JacekDanecki** [comment]
I've restarted llvm build, and this time build finished correctly.
```
Done install to / for dev-lang/llvm-8.0.0:8::arbor


 * Checking whether the GNU info directory needs updating...
 * No updates needed

Updating world

* Added 'dev-lang/llvm'

Summary:

succeeded: install dev-lang/llvm-8.0.0:8::arbor to ::installed
*** Messages log: //var/log/paludis/1564063317-install-dev-lang_llvm-8.0.0:8::arbor.messages
*** Creating alternatives module for llvm
```

**Comment by tgurr** [comment]
Glad to hear that, thanks and also for all your help and taking the time explaining everything to me! I didn't know you're actually trying out/using Exherbo.

**Pull request closed without merging**
