### PR TITLE
Fix redefinition of APIENTRY macro

### LINKED ISSUE #648: Redefinition of APIENTRY macro
Hi! The macro `APIENTRY` is defined both in `third_party/DirectX-Headers/include/wsl/winadapter.h` and `third_party/opengl_headers/GL/gl.h`. This causes a compiler warning with gcc12 and, owing to `-Werror`, a build error.

### PR DESCRIPTION
**Pull request by tpkessler**
Fixes #648

### CODE REVIEW

**Review by JablonskiMateusz — COMMENTED** [review]
third_party folders are taken as-is from external dependencies, we shouldn't modify them manually

**Comment by ph0b** [comment]
@JablonskiMateusz updating to latest stable version of DirectX-Headers may be a better option, it doesn't seem to redefine APIENTRY: https://github.com/microsoft/DirectX-Headers/blob/v1.610.2/include/wsl/winadapter.h

**Comment by tpkessler** [comment]
That would be even better! I'm currently using this patch to build the compute runtime for Arch Linux.

**Comment by JablonskiMateusz** [comment]
Hi @tpkessler. please add signed-off-by to your commit msg

**Comment by tpkessler** [comment]
Thanks for the hint @JablonskiMateusz. I also expanded the commit message explaining why the change is necessary.

**Comment by JablonskiMateusz** [comment]
@tpkessler please also correct commit msg to meet requirements defined here https://github.com/intel/compute-runtime/blob/master/CONTRIBUTING.md#commit-message-format

**Comment by JablonskiMateusz** [comment]
Fix merged https://github.com/intel/compute-runtime/commit/e1b429db40a7db4b54354eb371b870cddb469de1

**Pull request closed without merging**
