### PR TITLE
zeCommandListAppendMemoryFill fails to fill with 2 byte pattern

### PR DESCRIPTION
**Pull request by maleadt**
Rebase of https://github.com/intel/compute-runtime/pull/457, ref https://github.com/JuliaGPU/oneAPI.jl/issues/108.

### CODE REVIEW

**Comment by maleadt** [comment]
Updated. Please feel free to do such edits yourself, `Allow edits by maintainers` is enabled.

**Comment by aravindksg** [comment]
@maleadt are you modifying an existing commit and made changes on top? If so you might need to rebase only your changes of top of latest master? I'm currently seeing my previous commit + your changes in the diff view

**Comment by maleadt** [comment]
Yeah not sure how that happened, probably I amended the wrong commit. Fixed and rebased on top of latest master.

**Comment by maleadt** [comment]
@JablonskiMateusz @pengtu Bump; this has been an actual bug in oneAPI.jl for over 6 months, with a fix readily available for an equal amount of time. I'm not sure what's holding this back.

**Comment by JablonskiMateusz** [comment]
@maleadt merged as https://github.com/intel/compute-runtime/commit/1ee733e191691eea60cbe34dfb8d9e07a763f829

**Comment by maleadt** [comment]
Thanks!

**Pull request closed without merging**
